### ISSUE TITLE
Shebang parsing doesn't work for binary files

### ISSUE THREAD

**Issue by jyn514** [proot-me/proot-rs#8]
`String` only works on valid UTF-8 :(

**Comment by panicbit** [comment]
I'd like to look into this.

**Comment by panicbit** [comment]
If this project isn't completely abandoned...

**Comment by jyn514** [comment]
@panicbit right - I have an open PR at https://github.com/proot-me/proot-rs/pull/9 but it hasn't been reviewed in a year.

**Comment by oxr463** [comment]
@panicbit @jyn514 I would gladly assign either of you maintainer access for this rust implementation. I am currently the only "active" maintainer and to be honest, I barely have bandwidth for the main implementation.

**Comment by oxr463** [comment]
@KB5201314 has this been resolved with https://github.com/proot-me/proot-rs/pull/14?

**Comment by KB5201314** [comment]
> @KB5201314 has this been resolved with #14?


No, there still seems to be a problem with this part, because the args are not handled properly.

https://github.com/proot-me/proot-rs/blob/c34c9820afac3ae11eb8372db41102402a54652a/src/kernel/execve/shebang.rs#L168-L170

Maybe we have to replace the return value of this function from `Result<Option<PathBuf>>` with something else. Maybe `Result<Option<(PathBuf, Bstring)>>`?

**Comment by KB5201314** [comment]
Fixed in https://github.com/proot-me/proot-rs/pull/47
